# Generated by Django 2.2.5 on 2019-09-29 18:09

from django.db import migrations, models
import django.db.models.deletion
import yakumans.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0004_auto_20190922_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yakuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('yaku', yakumans.models.YakumansField()),
                ('is_tsumo', models.BooleanField()),
                ('picture', models.ImageField(blank=True, upload_to='yakumans/')),
                ('comment', models.TextField(blank=True)),
                ('loser', models.ForeignKey(blank=True, help_text='The player that has dealt in, if any', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yakumans_lost', to='players.Player')),
                ('winner', models.ForeignKey(help_text='The player who has got the yakuman', on_delete=django.db.models.deletion.CASCADE, related_name='yakumans_won', to='players.Player')),
            ],
        ),
    ]
