# Generated by Django 2.2.5 on 2019-09-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_player_discord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='discord_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='usma_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
