# Generated by Django 2.2.5 on 2019-09-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190914_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='discord_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Discord ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='usma_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='USMA ID'),
        ),
    ]
