# Generated by Django 2.2.5 on 2019-09-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chombos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chombo',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
