# Generated by Django 5.2.11 on 2026-02-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chombos', '0002_auto_20190920_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='chombo',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
    ]
