# Generated by Django 4.2.7 on 2023-11-26 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0004_auto_20190922_1346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('workspace_email', models.EmailField(max_length=254)),
                ('email_communication_consent', models.BooleanField()),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('discord_nickname', models.CharField(blank=True, max_length=30, verbose_name='Discord nickname')),
                ('discord_id', models.CharField(blank=True, max_length=30, verbose_name='Discord ID')),
                ('active_since', models.DateField()),
                ('active_until', models.DateField(blank=True, null=True)),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipFeePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('active_since', models.DateField()),
                ('active_until', models.DateField()),
                ('fee', models.DecimalField(decimal_places=6, max_digits=15)),
                ('members', models.ManyToManyField(blank=True, to='club.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BOARD', 'Board'), ('AUDIT_COMMITTEE', 'Audit committee')], max_length=20)),
                ('active_since', models.DateField()),
                ('active_until', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.member')),
            ],
        ),
    ]
