# Generated by Django 2.2.5 on 2019-09-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20190920_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
