# Generated by Django 2.2.5 on 2019-09-15 20:12

import badges.token_generator
import badges.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0011_auto_20190508_0153'),
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(help_text='The image must be square between 96x96 and 512x512 and must not exceed 256.0kB.', upload_to='', validators=[badges.validators.ImageMinResolutionValidator(96), badges.validators.ImageMaxResolutionValidator(512), badges.validators.image_square_validator, badges.validators.MaxFileSizeValidator(256000)])),
                ('endpoint_url', models.URLField(blank=True, null=True, verbose_name='Endpoint URL')),
                ('refresh_interval', models.DurationField(blank=True, null=True)),
                ('token', models.CharField(default=badges.token_generator.generate_token, editable=False, max_length=64, null=True)),
                ('owners', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('periodic_task', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask')),
                ('players', models.ManyToManyField(blank=True, to='players.Player')),
            ],
        ),
    ]
