# Generated by Django 2.2.5 on 2019-09-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='players',
            field=models.ManyToManyField(to='common.Player'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
