# Generated by Django 2.2.5 on 2019-09-06 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badges', '0002_auto_20190906_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
