# Generated by Django 2.2.5 on 2019-09-08 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badges', '0002_auto_20190906_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='owners',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='badge',
            name='players',
            field=models.ManyToManyField(blank=True, to='common.Player'),
        ),
    ]
