# Generated by Django 2.2.5 on 2019-09-08 18:07

import badges.token_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_auto_20190906_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='endpoint_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='refresh_interval',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='token',
            field=models.CharField(default=badges.token_generator.generate_token, editable=False, max_length=64, null=True),
        ),
    ]
