# Generated by Django 2.2.5 on 2019-09-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_auto_20190908_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
