# Generated by Django 2.2.5 on 2019-09-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0011_auto_20190508_0153'),
        ('badges', '0007_auto_20190908_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='periodic_task',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask'),
        ),
    ]
