# Generated by Django 2.2.5 on 2019-09-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0009_auto_20190915_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='endpoint_url',
            field=models.URLField(blank=True, null=True, verbose_name='Endpoint URL'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
