# Generated by Django 2.2.5 on 2019-09-15 18:47

import badges.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0010_auto_20190915_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(help_text='The image must be square between 96x96 and 512x512 and must not exceed 256.0kB.', upload_to='', validators=[badges.validators.ImageMinResolutionValidator(96), badges.validators.ImageMaxResolutionValidator(512), badges.validators.image_square_validator, badges.validators.MaxFileSizeValidator(256000)]),
        ),
    ]
